/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import AddUpdateDelete.Add;
import AddUpdateDelete.Delete;
import AddUpdateDelete.Update;
import LoginSignUp.login;
import LoginSignUp.signUp;
import com.mysql.cj.jdbc.Driver;
import com.sun.jdi.connect.spi.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import Main.Favourite;
import Main.Blocked;

/**
 *
 * @author meraj
 */
public class Blocked extends javax.swing.JFrame {

    private String user;
    /**
     * Creates new form MainInterface
     */
    public Blocked(String user) {
        initComponents();
        jLabelWelcome.setText("Welcome  " + user +"!");
        this.user=user;
          try {
//            Class.forName("com.mysql.jdbc.Driver");
            String db = "jdbc:mysql://localhost:3306/PhoneBook";
            
           java.sql.Connection con = DriverManager.getConnection(db,"root","root");
           String query = "SELECT CONCAT(first_name, ' ', last_name) AS full_name, phone_no,gmail,company FROM Contacts where blocked=true and username=?";

           PreparedStatement pstm = con.prepareStatement(query);
            pstm.setString(1,user);

             ResultSet rs = pstm.executeQuery();
             int i = 0; 
             while(rs.next())
             {
                 // example initial value
                i = i + 1;   // increment i by 1
                String id = String.valueOf(i);  // convert the int to String

                 String fullname = rs.getString("full_name");
                 String phoneNo = rs.getString("phone_no");
                 String gmail = rs.getString("gmail");
                 String company = rs.getString("company");
                 
                 String tbData[]={id,fullname,phoneNo,gmail,company};
                 DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                 tblModel.addRow(tbData);
                 
             }
             con.close();
            
        }  catch (SQLException ex) {
            Logger.getLogger(Blocked.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        jPanelBottom = new javax.swing.JPanel();
        Blocked = new javax.swing.JButton();
        Contacts = new javax.swing.JButton();
        Favourites = new javax.swing.JButton();
        jPanelSearch = new javax.swing.JPanel();
        jtxtSeach = new javax.swing.JTextField();
        jLSearchIcon = new javax.swing.JLabel();
        jButtonSearch = new javax.swing.JButton();
        jLabelUnblock = new javax.swing.JLabel();
        jLabelDelete = new javax.swing.JLabel();
        jLabelWelcome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuHome = new javax.swing.JMenu();
        menuSignOut = new javax.swing.JMenu();
        menuAboutUs = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PhoneBook-Blocked");

        panelMain.setBackground(new java.awt.Color(107, 241, 248));
        panelMain.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        jPanelBottom.setBackground(new java.awt.Color(0, 0, 0));
        jPanelBottom.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Blocked.setBackground(new java.awt.Color(153, 153, 153));
        Blocked.setText("Blocked");
        Blocked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlockedActionPerformed(evt);
            }
        });

        Contacts.setBackground(new java.awt.Color(153, 153, 153));
        Contacts.setText("Contacts");
        Contacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactsActionPerformed(evt);
            }
        });

        Favourites.setBackground(new java.awt.Color(153, 153, 153));
        Favourites.setText("Favourites");
        Favourites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavouritesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBottomLayout = new javax.swing.GroupLayout(jPanelBottom);
        jPanelBottom.setLayout(jPanelBottomLayout);
        jPanelBottomLayout.setHorizontalGroup(
            jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBottomLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Blocked)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Contacts)
                .addGap(271, 271, 271)
                .addComponent(Favourites)
                .addGap(16, 16, 16))
        );
        jPanelBottomLayout.setVerticalGroup(
            jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contacts)
                    .addComponent(Favourites)
                    .addComponent(Blocked, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelSearch.setBackground(new java.awt.Color(204, 204, 204));

        jtxtSeach.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jtxtSeach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtSeachMouseClicked(evt);
            }
        });
        jtxtSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSeachActionPerformed(evt);
            }
        });
        jtxtSeach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtSeachKeyPressed(evt);
            }
        });

        jLSearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchicons.png"))); // NOI18N

        jButtonSearch.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSearchMouseClicked(evt);
            }
        });
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabelUnblock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ublock.png"))); // NOI18N
        jLabelUnblock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUnblockMouseClicked(evt);
            }
        });

        jLabelDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleteIcon.png"))); // NOI18N
        jLabelDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDeleteMouseClicked(evt);
            }
        });

        jLabelWelcome.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabelUnblock, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLSearchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtSeach, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelUnblock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSearchLayout.createSequentialGroup()
                        .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSearch)
                            .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtxtSeach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLSearchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial_No", "Name", "Phone No", "G-Mail", "Company"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(jPanelBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addComponent(jPanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MenuHome.setText("New");
        MenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuHomeMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuHome);

        menuSignOut.setText("Sign Out");
        menuSignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSignOutMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSignOut);

        menuAboutUs.setText("About Us");
        menuAboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAboutUsMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAboutUs);

        menuHelp.setText("Help");
        menuHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHelpMouseClicked(evt);
            }
        });
        menuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelpActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSeachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSeachActionPerformed

    private void jtxtSeachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtSeachMouseClicked
        jtxtSeach.setText("");         // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSeachMouseClicked

    private void menuSignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSignOutMouseClicked
        JOptionPane.showMessageDialog(this,"Signed out!");
        this.dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_menuSignOutMouseClicked

    private void menuAboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAboutUsMouseClicked
          // TODO add your handling code here:
          new aboutUs(user).setVisible(true);
          this.dispose();
           
    }//GEN-LAST:event_menuAboutUsMouseClicked

    private void ContactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactsActionPerformed
      
      new Contacts(user).setVisible(true);
      this.dispose();
    }//GEN-LAST:event_ContactsActionPerformed

    private void FavouritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavouritesActionPerformed
        
        new Favourite(user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FavouritesActionPerformed

    private void BlockedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlockedActionPerformed
         new Blocked(user).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_BlockedActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
         DefaultTableModel tblModel1 = (DefaultTableModel)jTable1.getModel();
         tblModel1.setRowCount(0);
        try {
//            Class.forName("com.mysql.jdbc.Driver");
            String db = "jdbc:mysql://localhost:3306/PhoneBook";
            
           java.sql.Connection con = DriverManager.getConnection(db,"root","root");
           String query = "SELECT CONCAT(first_name, ' ', last_name) AS full_name, phone_no, gmail, company FROM Contacts WHERE username = ? AND blocked=true and CONCAT(first_name, ' ', last_name) LIKE ? ";

           PreparedStatement pstm = con.prepareStatement(query);
            pstm.setString(1,user);
            pstm.setString(2,"%"+jtxtSeach.getText()+"%");

             ResultSet rs = pstm.executeQuery();
             int i = 0; 
             while(rs.next())
             {
                 // example initial value
                i = i + 1;   // increment i by 1
                String id = String.valueOf(i);  // convert the int to String

                 String fullname = rs.getString("full_name");
                 String phoneNo = rs.getString("phone_no");
                 String gmail = rs.getString("gmail");
                 String company = rs.getString("company");
                 
                 String tbData[]={id,fullname,phoneNo,gmail,company};
                 DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                 tblModel.addRow(tbData);
                 
             }
             con.close();
            
        }  catch (SQLException ex) {
            Logger.getLogger(Contacts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSearchMouseClicked
        
    }//GEN-LAST:event_jButtonSearchMouseClicked

    private void menuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelpActionPerformed
        new Favourite(user).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_menuHelpActionPerformed

    private void jLabelUnblockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUnblockMouseClicked
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        if(selectedRow == -1){
             JOptionPane.showMessageDialog(this, "Please Select Contact!");
        } 
        else{
            String phoneNo = tblModel.getValueAt(jTable1.getSelectedRow(), 2).toString();
            String db = "jdbc:mysql://localhost:3306/PhoneBook"; 
            java.sql.Connection con = null;
           try{
               con = DriverManager.getConnection(db,"root","root");
               String query = "update contacts set blocked=false where phone_No=? and username=?";
               PreparedStatement pstmt = con.prepareStatement(query);
               pstmt.setString(1, phoneNo);
               pstmt.setString(2, user);
               int rows = pstmt.executeUpdate();
               if (rows>0)
               {
                   JOptionPane.showMessageDialog(this, "Unblocked Successfully!");
               }
               else
               {
                   JOptionPane.showMessageDialog(this, "Service Unavailable!");
               }
           }
           catch(SQLException ex)
           {
               ex.printStackTrace();
           }
        }
    }//GEN-LAST:event_jLabelUnblockMouseClicked

    private void jLabelDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDeleteMouseClicked
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        if(selectedRow == -1){
             JOptionPane.showMessageDialog(this, "Please Select Contact!");
        } 
        else{
            String phoneNo = tblModel.getValueAt(jTable1.getSelectedRow(), 2).toString();
            String db = "jdbc:mysql://localhost:3306/PhoneBook"; 
            java.sql.Connection con = null;
           try{
               con = DriverManager.getConnection(db,"root","root");
               String query = "delete from contacts where phone_no =? and blocked=true and username =?;";
               PreparedStatement pstmt = con.prepareStatement(query);
               pstmt.setString(1, phoneNo);
               pstmt.setString(2, user);
               int rows = pstmt.executeUpdate();
               if (rows>0)
               {
                   JOptionPane.showMessageDialog(this, "Deleted Successfully!");
               }
               else
               {
                   JOptionPane.showMessageDialog(this, "Service Unavailable!");
               }
           }
           catch(SQLException ex)
           {
               ex.printStackTrace();
           }
        }
    }//GEN-LAST:event_jLabelDeleteMouseClicked

    private void menuHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHelpMouseClicked
        new Help(user).setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_menuHelpMouseClicked

    private void jtxtSeachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSeachKeyPressed
       if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)jButtonSearchActionPerformed(null);

    }//GEN-LAST:event_jtxtSeachKeyPressed

    private void MenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuHomeMouseClicked
       new login().setVisible(true);
    }//GEN-LAST:event_MenuHomeMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Blocked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Blocked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Blocked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Blocked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                String user = null;
//                new Blocked(user).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Blocked;
    private javax.swing.JButton Contacts;
    private javax.swing.JButton Favourites;
    private javax.swing.JMenu MenuHome;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLSearchIcon;
    private javax.swing.JLabel jLabelDelete;
    private javax.swing.JLabel jLabelUnblock;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxtSeach;
    private javax.swing.JMenu menuAboutUs;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuSignOut;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
